;Common Lisp (SBCL 2.3.6)
(defun fizzbuzz (n)
    (when (< n 101)
        (cond
            ((= 0 (mod n 15))
                (write-string "FizzBuzz")
            )
            ((= 0 (mod n 3))
                (write-string "Fizz")
            )
            ((= 0 (mod n 5))
                (write-string "Buzz")
            )
            (t
                (write-string (write-to-string n))
            )
        )
        (terpri)
        (fizzbuzz (+ 1 n))
    )
)
(fizzbuzz 1)
